// Wails-generated bindings — regenerated by `wails build` or `wails dev`
import {
  ProjectInfo,
  Result,
  TestResult,
  SyncResult,
  DeployResult,
  AddProjectParams,
  RemoteEntry,
  GlobalConfig,
  ImportResult,
  ExportResult,
  SpeedTestResult,
} from "../../../types";

export function GetProjects(): Promise<ProjectInfo[]>;
export function AddProject(params: AddProjectParams): Promise<Result>;
export function RemoveProject(name: string): Promise<Result>;
export function UpdateProject(params: AddProjectParams): Promise<Result>;
export function TestProject(name: string): Promise<TestResult>;
export function ListRemote(
  projectName: string,
  remotePath: string
): Promise<RemoteEntry[]>;
export function SyncProject(
  projectName: string,
  dryRun: boolean
): Promise<SyncResult>;
export function DeployProject(projectName: string): Promise<DeployResult>;
export function GetLogs(projectName: string, n: number): Promise<string[]>;
export function GetConfig(): Promise<GlobalConfig>;
export function ImportProjects(
  filename: string,
  content: string,
  overwrite: boolean
): Promise<ImportResult>;
export function ExportProjects(
  name: string,
  format: string
): Promise<ExportResult>;
export function SpeedTest(projectName: string): Promise<SpeedTestResult>;
