// Wails-generated JS bindings — regenerated by `wails build` or `wails dev`

export function GetProjects() {
  return window["go"]["gui"]["App"]["GetProjects"]();
}
export function AddProject(params) {
  return window["go"]["gui"]["App"]["AddProject"](params);
}
export function RemoveProject(name) {
  return window["go"]["gui"]["App"]["RemoveProject"](name);
}
export function UpdateProject(params) {
  return window["go"]["gui"]["App"]["UpdateProject"](params);
}
export function TestProject(name) {
  return window["go"]["gui"]["App"]["TestProject"](name);
}
export function ListRemote(projectName, remotePath) {
  return window["go"]["gui"]["App"]["ListRemote"](projectName, remotePath);
}
export function SyncProject(projectName, dryRun) {
  return window["go"]["gui"]["App"]["SyncProject"](projectName, dryRun);
}
export function DeployProject(projectName) {
  return window["go"]["gui"]["App"]["DeployProject"](projectName);
}
export function GetLogs(projectName, n) {
  return window["go"]["gui"]["App"]["GetLogs"](projectName, n);
}
export function GetConfig() {
  return window["go"]["gui"]["App"]["GetConfig"]();
}
export function ImportProjects(filename, content, overwrite) {
  return window["go"]["gui"]["App"]["ImportProjects"](filename, content, overwrite);
}
export function ExportProjects(name, format) {
  return window["go"]["gui"]["App"]["ExportProjects"](name, format);
}
export function SpeedTest(projectName) {
  return window["go"]["gui"]["App"]["SpeedTest"](projectName);
}
